name: Compare

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

# NOTE: these permissions are needed for contender-compare to update PRs with a summary when it finishes running its reports
permissions:
  pull-requests: write
  contents: read

env:
  FOUNDRY_PROFILE: ci

jobs:
  contender-compare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create bin directory
        run: mkdir -p bin

      - name: Build reth (main)
        run: |
          cp reth_main_x86-64 ./bin/reth-main

      - name: Build reth (dev)
        run: |
          # cp reth_v1.11.0_x86-64 ./bin/reth-dev
          cp reth_main_x86-64 ./bin/reth-dev

      - name: Build contender
        run: |
          cp contender_x86-64 ./bin/contender

      - name: Run contender-compare
        uses: zeroXbrock/contender-compare@feat/report-summaries
        with:
          contender_bin_main: ./bin/contender
          contender_spam_args: --tps 200 -d 30 -a 10 erc20
          node_bin_main: ./bin/reth-main
          node_args_main: |
            node --dev --http -d
            --http.api debug,eth,trace,flashbots
            --txpool.pending-limit 100000
            --txpool.queued-limit 100000
            --txpool.basefee-limit 100000
            --txpool.blob-limit 10000
          node_bin_pr: ./bin/reth-dev
          node_args_pr: node --dev --http -d --http.port 9545
            --http.api debug,eth,trace,flashbots
            --txpool.pending-limit 100000
            --txpool.queued-limit 100000
            --txpool.basefee-limit 100000
            --txpool.blob-limit 10000
